[build]
  command = "yarn build"
  publish = "build"
[[plugins]]
  package = "@netlify/plugin-functions-install-core"
[[redirects]]
  from = "/*"
  to = "/.netlify/functions-internal/__render"
  status = 200